[versions]
agp = "8.13.2"
kotlin = "2.3.10"
mt-plugin = "3.0.0"
desugarJdkLibs = "2.1.5"
junit = "4.13.2"

[libraries]
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
junit = { module = "junit:junit", version.ref = "junit" }
mt-plugin-api = { module = "bin.mt.plugin:api", version.ref = "mt-plugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
mt-plugin = { id = "bin.mt.plugin", version.ref = "mt-plugin" }
